import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/header';
import { SideNav } from '@/components/side-nav';
import { Modal } from '@/components/modal';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Brest Bar',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={(inter.className, 'antialised flex h-screen flex-col')}>
        <Header />
        <div className='flex h-full overflow-hidden'>
          <SideNav />
          <div className='flex-grow'>{children}</div>
        </div>{' '}
        <Modal />
      </body>
    </html>
  );
}
